name: Sonar Analysis Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  sonar:
    uses: asi-alliance/security-workflows-public/.github/workflows/sonar.yml@master
    secrets: inherit
